import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { AI_DISCLOSURE } from "@/lib/ai-disclosure";
import { SITE_URL, organizationJsonLd, pageMetadata, serializeJsonLd } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  path: "/about",
  title: "About and how it's made",
  description:
    "What The Forward Pass covers, how each daily issue is collected, written and fact-checked against its sources, and who publishes it.",
});

const aboutJsonLd = {
  "@type": "AboutPage",
  url: `${SITE_URL}/about`,
  name: "About The Forward Pass",
  about: { "@id": organizationJsonLd["@id"] },
  publisher: organizationJsonLd,
  inLanguage: "en",
};

export default function About() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(aboutJsonLd) }} />
      <LegalPage
        eyebrow="The publication"
        title="About"
        lede={
          <p>
            The Forward Pass is a daily newsletter for people who build with AI. Each morning it covers
            what changed in AI engineering: model releases and benchmarks, agents and coding tools, research
            worth reading, inference and infrastructure, developer tools, and open-source weights, repos and
            datasets.
          </p>
        }
      >

        <h2>Written by AI, checked against sources</h2>
        <p>{AI_DISCLOSURE}</p>
        <p>
          Every daily issue is produced by an automated editorial pipeline. The steps below run every day,
          in this order, and an issue that fails a check is not published.
        </p>
        <ul>
          <li>
            <strong>Collection.</strong> Every two hours the engine reads an audited catalogue of more than
            850 sources: lab and company blogs, changelogs and release notes, papers, GitHub releases,
            publication feeds and developer communities. It also records attention signals such as Hacker
            News points and comments and GitHub stars.
          </li>
          <li>
            <strong>Selection.</strong> Code groups duplicate reports of the same announcement and ranks
            them by freshness, source and attention. A model triages the shortlist, and an editor model picks
            the stories for the issue.
          </li>
          <li>
            <strong>Fact sheets.</strong> For each chosen story, claims are extracted from the primary
            source together with the passage that supports them.
          </li>
          <li>
            <strong>Writing.</strong> A writer model drafts the issue from those fact sheets only. Every
            story links to its primary source.
          </li>
          <li>
            <strong>Checking.</strong> A model from a different model family checks each sentence against
            the captured sources. Unsupported claims are cut or rewritten and checked again, and numbers that
            do not appear in a source are removed.
          </li>
          <li>
            <strong>Publishing.</strong> The issue is published to the{" "}
            <Link href="/archive">archive</Link> and emailed around 05:45 UTC. Its cover illustration is
            generated by an image model from the lead story.
          </li>
        </ul>
        <p>
          Today the editor and writer run on Claude Opus 5.5, and triage, fact extraction and checking run
          on GPT-6 Luna, all through the Vercel AI Gateway. The models change as better ones ship.
        </p>

        <h2>Editorial articles</h2>
        <p>
          The <Link href="/archive?section=editorial">editorial archive</Link> has two kinds of long-form
          piece written by the same pipeline, both bylined to The Forward Pass research desk and labelled as
          AI-generated:
        </p>
        <ul>
          <li>
            <strong>The Sunday deep dive.</strong> The week&apos;s most consequential story, researched
            across all of its sources and checked sentence by sentence like the daily issue. Its
            &ldquo;Try it&rdquo; steps are copied from the official documentation and say what each one
            needs, such as an account, an API key, approval or specific hardware. We do not run them.
          </li>
          <li>
            <strong>The monthly data report.</strong> What got traction in the month, from our own
            measurements of GitHub stars and Hacker News discussion on everything we collect. Every number is
            computed by code, and the text may only use numbers from those tables.
          </li>
        </ul>
        <p>Pieces written by people carry their author&apos;s name.</p>

        <h2>Plans</h2>
        <p>
          The general daily issue is free. Personal readers get an issue built around their interests, and
          Professional adds weekly research on their brief. See <Link href="/pricing">pricing</Link>.
        </p>

        <h2>Corrections and contact</h2>
        <p>
          If an issue gets something wrong, email{" "}
          <a href="mailto:hello@withradian.com">hello@withradian.com</a> with the issue date and the source.
          The Forward Pass is published by Kaloyan Gamtchev in Vienna, Austria (see the{" "}
          <Link href="/imprint">imprint</Link>).
        </p>
      </LegalPage>
    </>
  );
}
